definitions:
  workflow: &base_workflow
    environment:
      groups: 
       - ios_creds
      xcode: latest
      vars:
        XCODE_PROJECT: "Wikipedia.xcodeproj"
        XCODE_SCHEME: "Wikipedia"
    triggering:
      events:
        - push
    scripts:
      - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
        script: keychain initialize
      - name: Fetch signing files
        script: | 
            app-store-connect fetch-signing-files io.wikimedia.wikipedia --type IOS_APP_STORE --create
            app-store-connect fetch-signing-files io.wikimedia.wikipedia.WikipediaStickers --type IOS_APP_STORE --create
      - name: Use system default keychain
        script: keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Upgrade brew
        script: brew install clang-format swiftlint || brew upgrade clang-format swiftlint
      - name: Installing scripts
        script: ./scripts/setup
      # - name: Building projects
      #   script: |
      #     time xcodebuild clean build -project $XCODE_PROJECT -scheme $XCODE_SCHEME -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=16.2' -configuration Debug CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
      - name: Running tests
        script: |
          time xcodebuild clean test -project $XCODE_PROJECT -scheme $XCODE_SCHEME -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=16.2'

workflows:
  wikipedia-mac-mini-m1:
    <<: *base_workflow
    name: Wikipedia Workflow with Mac mini M1
    instance_type: mac_mini_m1
  wikipedia-mac-mini-m2:
    <<: *base_workflow
    name: Wikipedia Workflow with Mac mini M2
    instance_type: mac_mini_m2
